server:
  port: 8080

spring:
  profiles:
    active: local
  mvc:
    throw-exception-if-no-handler-found: true

#分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#mybatis&通用mapper相关配置
mybatis:
  type-aliases-package: com.jiajun.starter.model
  mapper-locations: classpath:mapper/*.xml
mapper:
  not-empty: false
  identity: MYSQL

#swagger文档相关配置
swagger:
  enabled: true
  title: 云南职校项目接口文档
  description: 云南职校项目相关接口说明
  version: 1.0
  base-package: com.jiajun.starter
  authorization:
    key-name: Authorization

#打印mybatis动态生成的sql语句
logging:
  level:
    com.jiajun.starter.ucenter.mapper: debug
