server:
  port: 8080

spring:
  profiles:
    active: local
  mvc:
    throw-exception-if-no-handler-found: true
  messages:
    basename: i18n/ucenter/message
    encoding: UTF-8

#分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#mybatis&通用mapper相关配置
mybatis:
  type-aliases-package: com.jiajun.starter.model
  mapper-locations: classpath:mapper/*.xml
mapper:
  not-empty: false
  identity: MYSQL

#swagger文档相关配置
swagger:
  enabled: true
  title: 项目接口文档
  description: 项目相关接口说明
  version: 1.0
  base-package: com.jiajun.starter
  authorization:
    key-name: token

