version: "3.1"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7.25
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  redis:
    container_name: redis
    image: redis:5.0.3
    restart: always
    ports:
      - "6379:6379"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8000:8080"
